### ISSUE TITLE
首页无法渲染

### ISSUE THREAD

**Issue by the-sword** [Molunerfinn/hexo-theme-melody#9]
使用npm install hexo-renderer-jade hexo-renderer-stylus --save安装插件时，一直报以下错误
 Jade has been renamed to pug, please install the latest version of pug instead of jade

并且在点击文章标题时，无法显示文章页，报错
\themes\melody\layout\post.pug:32
    30|             .post-meta-wordcount
    31|               span= _p('post.wordcount') + ': '
  > 32|               span.word-count= wordcount(page.content)
    33|               span.post-meta__separator |
    34|               span= _p('post.min2read', min2read(page.content, {cn: 350, en: 160}))
    35|   else
wordcount is not a function

**Comment by Molunerfinn** [comment]
你如果开启了字数统计，应当安装一下`hexo-wordcount`这个插件。我在文档里应该有[说明](https://molunerfinn.com/hexo-theme-melody-doc/#/additional-package-support?id=word-counting)
`npm install hexo-wordcount` or `yarn add hexo-wordcount`
另外`Jade has been renamed to pug, please install the latest version of pug instead of jade`这个是个warning，是因为Jade已经改名为pug了，不过官方的`hexo-renderer-jade`还有引用jade而已，不必关注。
